# Generated by Django 4.0.3 on 2022-04-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0003_delete_mascotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animal', models.CharField(max_length=20, verbose_name='nombre_animal')),
                ('raza', models.CharField(max_length=20, verbose_name='raza')),
            ],
        ),
    ]
